<nav>
    <div class="nav-left">
        <img src="images/logo.png" alt="Logo" class="logo"></a>
        <select name="menu" id="menu" onchange="navigateMenu()">
            <option value="home" selected>Home</option>
            <option value="pets">Pets</option>
            <option value="add-more">Add More</option>
            <option value="gallery">Gallery</option>
        </select>
    </div>
    <form class="search-form">
        <input type="text" placeholder="Search...">
    </form>
</nav>
